- name: Upload XLSX to FTP
  uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: ${{ secrets.FTP_HOST }}
    username: ${{ secrets.FTP_USER }}
    password: ${{ secrets.FTP_PASS }}
    protocol: ftp
    port: 21
    passive: true
    timeout: 60000
    local-dir: ./
    server-dir: /Bobby/Reverb/
    include: |
      ReverbCityMusic.xlsx
    exclude: |
      **
